heat_template_version: 2013-05-23

description: |
  Deploy tsung for load testing with a multi node.

parameters:
  tsung_nodes:
    description: Number of tsung nodes to deploy for load testing
    type: number
    default: 0
    constraints:
      - range:
        min: 0
        max: 12

  key_name:
    description: Name of the key to add to the build of each server
    type: string

resources:
  tsung-master:
    type: Rackspace::Cloud::Server
    properties:
      flavor: 2 GB Performance
      image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      name: tsung-master
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
          #!/bin/bash -v
          apt-get update
          apt-get install build-essential debhelper erlang-nox erlang-dev python-matplotlib gnuplot libtemplate-perl sphinx-common
          wget http://tsung.erlang-projects.org/dist/tsung-1.5.1.tar.gz
          tar -zxvf tsung-1.5.1.tar.gz
          cd tsung-1.5.1
          ./configure
          make
          make deb
          cd ..
          dpkg -i tsung_1.5.1-1_all.deb

  tsung-slave:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: master_count }
      resource_def:
        type: Rackspace::Cloud::Server
        properties:
          flavor: 2 GB Performance
          image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
          name: protheus-master
          key_name: { get_param: key_name }
          user_data:
            str_replace:
              template: |
                #!/bin/bash -v
                apt-get update
              params:
                input_tsung_master: { get_attr: [tsung-master, first_address]}